remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Trường Tiểu học Lê Văn Sĩ
description: Tin học
github:
  owner_name: Phong Do
  repository_name: LVS
- owner_url: lvs.lilw.dev
- repository_url: lvs.lilw.dev
